spring.application.name=tss_evaluation2_emi_schedular_app

spring.datasource.url=jdbc:postgresql://localhost:5432/tss_evaluation2_emi_schedular_app
spring.datasource.username=postgres
spring.datasource.password=Temp@123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# These keys must match the @Value("${...}") placeholders used in JwtTokenProvider
app.jwt-secret=qjKMJMERaSrufNhGUEEU1AmrgrULMgmNPdfmMmVXEsAaE5eFsLsscqAJkvgv4S0OAjvV+KXVRV2TXOu5/QN2yg==
app.jwt-expiration-milliseconds=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devbhut21@gmail.com
spring.mail.password=sahbceyctvzligjr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# admin
app.default-admin.full-name=Admin
app.default-admin.email=admin@gmail.com
app.default-admin.password=123456

# loan officer
app.default-loan-officer.full-name=Loan Officer
app.default-loan-officer.email=officer@gmail.com
app.default-loan-officer.password=123456

otp.cleanup.cron=0 */10 * * * *