spring.application.name=tss_evaluation2_emi_schedular_app

spring.datasource.url=jdbc:postgresql://localhost:5432/tss_evaluation2_emi_schedular_app
spring.datasource.username=postgres
spring.datasource.password=Temp@123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# admin
app.default-admin.full-name=Admin
app.default-admin.email=admin@gmail.com
app.default-admin.password=123456

# loan officer
app.default-loan-officer.full-name=Loan Officer
app.default-loan-officer.email=officer@gmail.com
app.default-loan-officer.password=123456